# This is a basic workflow to help you get started with Actions

name: CHECKOUT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 2,8,14,20 * * *'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          fetch-depth: '0'

      - name: Git config
        run: |
          git config --global user.email "acooler15@foxmail.com"
          git config --global user.name "acooler15"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

      - name: Git submodule update
        run: |
          git submodule update --init --remote --force 
          [ -n "$(git status --untracked-files=no -s)" ] && git commit -am "auto update" || echo "no update"

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Git push
        run: git push origin ${{ steps.extract_branch.outputs.branch }}

